### ISSUE TITLE
Nuri - Test Registration

### ISSUE THREAD

**Issue by memetnur** [DataChallenge-N/FS22#1]
Name: Nurdzane Memeti
ZHAW Kürzel: memetnur

**Comment by ratnanil** [comment]
Hey Nuri, can you make another test registration @memetnur ? I updated the contact form

**Comment by memetnur** [comment]
@ratnanil I did another test registration

**Comment by ratnanil** [comment]
Hey Nuri! 

 I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?

We are looking forward to this event!

Cheers,

Nils
