### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by memetnur** [DataChallenge-N/FS22#2]
### Name

Nuri

### ZHAW Username

memn

### Your status at ZHAW (optional)

Master student

### Your institute (optional)

ICLS Institut für Computational Life Sciences

**Comment by ratnanil** [comment]
Hey Nuri!

I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf)  and send it back to me (you can also send it via mail to [rata@zhaw.ch](mailto:rata@zhaw.ch))?

We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment]
Dear Nuri, I haven't received the NDA back from you yet. Are you still interested in participating?

**Comment by ratnanil** [comment]
If you have **any questions**, we can schedule [a meeting](https://calendly.com/rata-zhaw/)

**Comment by ratnanil** [comment]
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by memetnur** [comment]
Thank you for your message @ratnanil you find here the NDA. yes i would lovely participate to the DataChallange. [DataChallangeNDA.pdf](https://github.com/DataChallenge-N/FS22/files/8863293/DataChallangeNDA.pdf)

**Comment by ratnanil** [comment]
Hi Nuri! I haven't received a submission for the DataChallenge from you yet. Have you encountered any issues? Remember that you can always [contact me ](https://www.zhaw.ch/de/ueber-uns/person/rata/) or easily [schedule an appointment](https://calendly.com/rata-zhaw/).

**Comment by memetnur** [comment]
@ratnanil hey nils I just had my exam finished, later I will have a look at DataChallange, sry for my delay!!! did the student submit
