### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by cewinharhar** [DataChallenge-N/FS22#5]
### Name

kevin yar

### ZHAW Username

mohamkev

### Your status at ZHAW (optional)

Master student

### Your institute (optional)

ICLS Institut für Computational Life Sciences

**Comment by ratnanil** [comment]
Dear Kevin

It would be really cool if you participate in the data challenge. I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?

We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment]
Dear Kevin, I haven't received the NDA back from you yet. Are you still interested in participating?

**Comment by ratnanil** [comment]
If you have **any questions**, we can schedule [a meeting](https://calendly.com/rata-zhaw/)

**Comment by ratnanil** [comment]
Hey Kevin! Thank you for providing me with your NDA. I've sent you an invitation for read access to a private repo holding the dataset. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by ratnanil** [comment]
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by ratnanil** [comment]
As we discussed via zoom, you regrettably won't take part in the DataChallenge and Hackdays. 😞  I will close this issue now.
