### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by HerbertDaMoth** [DataChallenge-N/FS22#9]
### Name

Leandro Haller

### ZHAW Username

hallelea

### Your status at ZHAW (optional)

Bachelor student

### Your institute (optional)

IUNR Institut für Umwelt und Natürliche Ressourcen

**Comment by ratnanil** [comment]
Dear Leandro

It would be really cool if you participate in the data challenge. I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?

We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment]
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by ratnanil** [comment]
Hi Leandro! I haven't received a submission for the DataChallenge from you yet. Have you encountered any issues? Remember that you can always [contact me ](https://www.zhaw.ch/de/ueber-uns/person/rata/) or easily [schedule an appointment](https://calendly.com/rata-zhaw/).

**Comment by ratnanil** [comment]
Hey Leandro, are you getting these messages?

**Comment by HerbertDaMoth** [comment]
Hey Nils, I sadly didn't have time to look at the data and I won't have time in the next days. June is way more hectic them I thought. I sadly won't have time to participate in this DataChallenge.
Best Leandro

**Comment by ratnanil** [comment]
That's really too bad, we would have liked to have you on board! In this case, I will close this issue now 😞
